
(IN-PACKAGE "COMPILER") 
(PROCLAIM '(FTYPE (FUNCTION (T) FIXNUM) F-TYPE)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T) FIXNUM) PROCLAIMED-ARGD ANALYZE-REGS
            ANALYZE-REGS1)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T T) *) WT-INLINE C2COMPILER-LET C2IF C2FLET
            C2LABELS)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T T T) *) C1DM-VL C1DM-V C2RETURN-FROM
            C2APPLY-OPTIMIZE C2DM)) 
(PROCLAIM '(FTYPE (FUNCTION (T T *) *) T3DEFUN-AUX)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T T T) T) T3DEFUN-VARARG T3DEFUN-NORMAL
            MY-CALL WT-GLOBAL-ENTRY C1MAKE-VAR C2STRUCTURE-REF C2SWITCH
            C2CALL-GLOBAL C2CALL-UNKNOWN-GLOBAL)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T T) T) BOOLE3 WT-INLINE-COND WT-INLINE-FIXNUM
            WT-INLINE-INTEGER C1MAP-FUNCTIONS WT-INLINE-CHARACTER
            WT-INLINE-LONG-FLOAT WT-INLINE-SHORT-FLOAT C2MAPCAR C2MAPC
            C2MAPCAN FIX-DOWN-ARGS WT-IF-PROCLAIMED SET-VAR
            C1STRUCTURE-REF1 ASSIGN-DOWN-VARS CJF C2MULTIPLE-VALUE-BIND
            C2PRINC C1DM TOO-MANY-ARGS T3DEFCFUN TOO-FEW-ARGS
            CMP-EXPAND-MACRO ADD-FUNCTION-PROCLAMATION
            ADD-FUNCTION-DECLARATION CAN-BE-REPLACED* C2LET*
            SUBLIS1-INLINE CHECK-VDECL GET-INLINE-INFO C2TAGBODY C2GO
            C2CASE AND-FORM-TYPE CHECK-FORM-TYPE C2FUNCALL-SFUN CJT
            C2LET ADD-FAST-LINK INLINE-TYPE-MATCHES C2PROGV)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T *) T) INLINE-ARGS C2FUNCALL C2LAMBDA-EXPR)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T T T T) T) T3DEFUN-LOCAL-ENTRY T3DEFUN
            T3LOCAL-DCFUN T3LOCAL-FUN C1APPLY-OPTIMIZE C2STRUCTURE-SET
            T2DEFUN T2DEFENTRY T3DEFENTRY)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T T T T T) T) DEFSYSFUN T2DEFMACRO T3DEFMACRO)) 
(PROCLAIM '(FTYPE (FUNCTION (T T T *) T) WT-SIMPLE-CALL)) 
(PROCLAIM '(FTYPE (FUNCTION NIL *) WT-FASD-DATA-FILE WT-DATA-FILE)) 
(PROCLAIM
    '(FTYPE (FUNCTION NIL T) WT-NEXT-VAR-ARG WT-FIRST-VAR-ARG
            CLOSE-INLINE-BLOCKS WT-DATA-BEGIN WT-DATA-END C1T
            ADD-LOAD-TIME-SHARP-COMMA RESET-TOP CVS-PUSH WT-CVARS
            PRINT-CURRENT-FORM INIT-ENV INC-INLINE-BLOCKS WT-C-PUSH
            C1NIL VS-PUSH BABOON TAIL-RECURSION-POSSIBLE CCB-VS-PUSH
            WFS-ERROR)) 
(PROCLAIM '(FTYPE (FUNCTION (*) *) INLINE-BOOLE3)) 
(PROCLAIM
    '(FTYPE (FUNCTION (*) T) MAKE-INFO FCALLN-INLINE MAKE-BLK
            LIST-INLINE LIST*-INLINE MAKE-TAG MAKE-FUN CS-PUSH MAKE-VAR
            WT-CLINK)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T) *) SET-LOC C2OR T1EXPR C2EXPR C2PROGN
            T1EVAL-WHEN CMP-TOPLEVEL-EVAL WT-TO-STRING CMP-EVAL WT-LOC
            WT-FIXNUM-LOC WT-CHARACTER-LOC WT-LONG-FLOAT-LOC
            WT-SHORT-FLOAT-LOC C2AND)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T) T) DECLARATION-TYPE WT-VS-BASE ADD-OBJECT
            C2BIND VOLATILE C2FUNCALL-AUX VAR-NAME C1FUNOB VAR-REF
            INFO-P VAR-REF-CCB WT-FUNCTION-LINK VAR-LOC WT-FUNCALL-C
            VAR-TYPE FIXNUM-LOC-P VAR-REGISTER CHARACTER-LOC-P
            SAVE-FUNOB LONG-FLOAT-LOC-P SHORT-FLOAT-LOC-P
            VERIFY-DATA-VECTOR WT-DATA-PACKAGE-OPERATION C1MAPCAR
            C1MAPLIST ARGS-CAUSE-SIDE-EFFECT T1ORDINARY C1MAPC
            NAME-TO-SD C1MAPL C1PROGN WT-H1 T1PROGN PROCLAIM
            CHECK-DOWNWARD C1MAPCAN PROCLAMATION C1VAR CHECK-VREF
            C1MAPCON VAR-P C1VREF ADD-SYMBOL WT-VS* VARARG-P FLAGS-POS
            MAXARGS C1CATCH C1MULTIPLE-VALUE-CALL C1EXPR
            C1UNWIND-PROTECT WT-CCB-VS C1MULTIPLE-VALUE-PROG1
            C2DM-RESERVE-VL INLINE-BOOLE3-STRING INFO-CHANGED-VARS
            AET-C-TYPE RESULT-TYPE C1THROW C1VALUES C2DM-RESERVE-V
            INFO-REFERRED-VARS C2VALUES INFO-TYPE GET-INCLUDED
            C1STRUCTURE-REF SET-PUSH-CATCH-FRAME C1MULTIPLE-VALUE-SETQ
            INFO-SP-CHANGE CONS-TO-LISTA C1BLOCK C2VAR-KIND
            INFO-VOLATILE WT-VAR-DECL SET-UP-VAR-CVS
            C1MULTIPLE-VALUE-BIND C1STRUCTURE-SET CONSTANT-FOLD-P
            C1RETURN-FROM C1PRINC C1SHARP-COMMA PARSE-CVSPECS
            C1DOWNWARD-FUNCTION C1DEFINE-STRUCTURE C2DOWNWARD-FUNCTION
            C1TERPRI T1DEFUN C1APPLY T1DEFMACRO
            WT-DOWNWARD-CLOSURE-MACRO REPLACE-CONSTANT T1CLINES
            THE-PARAMETER T1DEFCFUN C1FUNCALL T1DEFENTRY C1DM-BAD-KEY
            C1RPLACA FASD-STREAM T1DEFLA C2RPLACA FASD-TABLE C1RPLACD
            BLK-P FASD-EOF C2RPLACD FASD-DIRECTION T2ORDINARY C1MEMQ
            FASD-PACKAGE T2DECLARE C1QUOTE C1MEMBER FASD-INDEX
            C1FUNCTION FASD-FILEPOS C2FUNCTION C1ASSOC BLK-NAME
            FASD-TABLE_LENGTH C1THE BLK-REF FASD-EVALD_FORMS
            C1EVAL-WHEN C1GET BLK-REF-CLB T3CLINES C1DECLARE C2GET
            BLK-REF-CCB C1COMPILER-LET C1NTH-CONDITION BLK-EXIT C1NTH
            BLK-VALUE-TO-GO CTOP-WRITE WT-SYMBOL-FUNCTION
            C1NTHCDR-CONDITION BLK-VAR C1NTHCDR NAME-SD1
            UNDEFINED-VARIABLE T1DEFINE-STRUCTURE REGISTER
            C1RPLACA-NTHCDR C1LIST-NTH PUSH-DATA-INCF WT-DATA1
            C1BOOLE-CONDITION C1BOOLE3 FUNCTION-ARG-TYPES
            CMP-MACROEXPAND C1IF C1ASH-CONDITION SCH-LOCAL-FUN
            CMP-MACROEXPAND-1 C1ASH SCH-GLOBAL C1LENGTH VAR-KIND
            ADD-CONSTANT ADD-REG1 ADD-LOOP-REGISTERS GET-ARG-TYPES WT1
            C1ADD-GLOBALS C2TAGBODY-CCB GET-RETURN-TYPE REP-TYPE
            C2TAGBODY-CLB WRITE-BLOCK-OPEN C1FLET GET-LOCAL-ARG-TYPES
            C2TAGBODY-LOCAL GET-LOCAL-RETURN-TYPE C2TAGBODY-BODY C1LET
            C1LABELS WT-SWITCH-CASE C1LET* C2GO-CCB C1MACROLET C2GO-CLB
            C1STACK-LET C2GO-LOCAL INLINE-POSSIBLE C1TAGBODY C1OR FUN-P
            SAVE-AVMA WT-LIST C1GO C1LOCAL-CLOSURE TAG-P C1AND
            C1LOCAL-FUN C1SWITCH CMP-MACRO-FUNCTION OBJECT-TYPE C1ECASE
            RESET-INFO-TYPE C2EXPR* TAG-NAME DEFAULT-INIT TAG-REF
            TAG-REF-CLB SET-RETURN PUSH-ARGS WT-DOWN TAG-REF-CCB
            SET-TOP PUSH-ARGS-LISPCALL TAG-LABEL
            NEED-TO-SET-VS-POINTERS INLINE-TYPE C2LOCATION
            TAG-UNWIND-EXIT C2VAR TAG-VAR FUN-NAME C1SETQ TAG-SWITCH
            FUN-REF SYSTEM:UNDEF-COMPILER-MACRO WT-VS FUN-REF-CCB
            FIX-OPT C1PROGV WT-VV UNWIND-NO-EXIT FUN-CFUN CLINK WT-CAR
            FUN-LEVEL C1PSETQ TYPE-FILTER WT-CDR C1FMLA-CONSTANT
            WT-CADR FUNCTION-RETURN-TYPE)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T) *) C2BLOCK-LOCAL C1SYMBOL-FUN
            C2RETURN-LOCAL C2BLOCK C1BODY C2DECL-BODY WT-INLINE-LOC)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T *) T) C1CASE UNWIND-EXIT WT-COMMENT CMPERR
            ADD-INIT CMPWARN CMPNOTE WT-INTEGER-LOC C1LAMBDA-EXPR
            FAST-LINK-PROCLAIMED-TYPE-P WT-CVAR)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T) T) SET-BDS-BIND WT-FIXNUM-VALUE UNWIND-BDS
            RESULT-TYPE-FROM-ARGS WT-CHARACTER-VALUE C2BIND-LOC
            WT-LONG-FLOAT-VALUE C2BIND-INIT WT-SHORT-FLOAT-VALUE
            SHIFT>> ADD-INFO SHIFT<< ARGS-INFO-REFERRED-VARS
            COMPILER-CLEAR-COMPILER-PROPERTIES MAYBE-EVAL
            PUSH-CHANGED-VARS C2BLOCK-CCB C1CONSTANT-VALUE C2BLOCK-CLB
            CMPFIX-ARGS MAKE-INLINE-STRING C1FMLA C1LAMBDA-FUN
            C2LAMBDA-EXPR-WITH-KEY MULTIPLE-VALUE-CHECK
            C2LAMBDA-EXPR-WITHOUT-KEY CO1CONSTANT-FOLD C1ARGS C2CATCH
            C2MULTIPLE-VALUE-CALL C2EXPR-TOP ADD-DEBUG-INFO C1EXPR*
            C2UNWIND-PROTECT C2RETURN-CCB C2MULTIPLE-VALUE-PROG1
            C2RETURN-CLB WT-REQUIREDS STRUCT-TYPE-OPT
            C2THROW C2DM-BIND-LOC WT-V*-MACROS C2DM-BIND-INIT
            C2MULTIPLE-VALUE-SETQ FAST-READ CFAST-WRITE
            WT-MAKE-DCLOSURE C2APPLY C2EXPR-TOP* C1PROGN* ADD-ADDRESS
            T2SHARP-COMMA C2MEMBER!2 COMPILER-DEF-HOOK C2ASSOC!2
            SYSTEM::ADD-DEBUG WT-MAKE-CCLOSURE SET-DBIND
            C2LIST-NTH-IMMEDIATE CONVERT-CASE-TO-SWITCH PROCLAIM-VAR
            CO1LDB CO1EQL JUMPS-TO-P CO1TYPEP COERCE-LOC CO1SCHAR
            ARGS-INFO-CHANGED-VARS CO1CONS CAN-BE-REPLACED CO1READ-BYTE
            CO1READ-CHAR CO1WRITE-BYTE CO1WRITE-CHAR WT-VAR
            CO1VECTOR-PUSH CO1SPECIAL-FIX-DECL C1DECL-BODY CO1SUBLIS
            CO1STRUCTURE-PREDICATE C2STACK-LET SET-VS GET-INLINE-LOC
            NEED-TO-PROTECT TYPE-AND SET-JUMP-TRUE SET-JUMP-FALSE
            C2CALL-LOCAL C2CALL-LAMBDA COERCE-LOC-STRUCTURE-REF C1SETQ1
            C2PSETQ C2SETQ TYPE>= CHECK-FNAME-ARGS INLINE-PROC)) 