
(COMMON-LISP::IN-PACKAGE "SYSTEM") 
(COMMON-LISP::PROCLAIM
    '(COMMON-LISP::FTYPE
         (COMMON-LISP::FUNCTION
             ((COMMON-LISP::VECTOR COMMON-LISP::CHARACTER
                  COMMON-LISP::*)
              (COMMON-LISP::INTEGER -9223372036854775808
                  9223372036854775807))
             COMMON-LISP::FIXNUM)
         SYSTEM::ATOI)) 
(COMMON-LISP::PROCLAIM
    '(COMMON-LISP::FTYPE
         (COMMON-LISP::FUNCTION
             ((COMMON-LISP::INTEGER -9223372036854775808
                  9223372036854775807)
              COMMON-LISP::T)
             COMMON-LISP::T)
         SYSTEM::SMALLNTHCDR)) 
(COMMON-LISP::PROCLAIM
    '(COMMON-LISP::FTYPE
         (COMMON-LISP::FUNCTION
             ((COMMON-LISP::INTEGER -9223372036854775808
                  9223372036854775807)
              (COMMON-LISP::INTEGER -9223372036854775808
                  9223372036854775807))
             COMMON-LISP::FIXNUM)
         SYSTEM::ROUND-UP)) 
(COMMON-LISP::PROCLAIM
    '(COMMON-LISP::FTYPE
         (COMMON-LISP::FUNCTION
             (COMMON-LISP::T
                 (COMMON-LISP::INTEGER -9223372036854775808
                     9223372036854775807)
                 COMMON-LISP::T COMMON-LISP::T)
             COMMON-LISP::T)
         SYSTEM::BIGNTHCDR)) 
(COMMON-LISP::PROCLAIM
    '(COMMON-LISP::FTYPE
         (COMMON-LISP::FUNCTION
             (COMMON-LISP::T
                 (COMMON-LISP::INTEGER -9223372036854775808
                     9223372036854775807)
                 (COMMON-LISP::INTEGER -9223372036854775808
                     9223372036854775807)
                 COMMON-LISP::T COMMON-LISP::T)
             COMMON-LISP::T)
         SYSTEM::QUICK-SORT)) 
(COMMON-LISP::PROCLAIM
    '(COMMON-LISP::FTYPE
         (COMMON-LISP::FUNCTION (COMMON-LISP::T) COMMON-LISP::T)
         SYSTEM::S-DATA-HAS-HOLES SYSTEM::DIRECTORY-LIST-CHECK
         SYSTEM::NEXT-STACK-FRAME FPE::XMM-LOOKUP
         SYSTEM::MAKE-KCL-TOP-RESTART COMMON-LISP::PATHNAME
         SYSTEM::INSPECT-VECTOR COMMON-LISP::NAMESTRING
         COMMON-LISP::LOGNOT SYSTEM::NORMALIZE-TYPE
         SLOOP::PARSE-NO-BODY SYSTEM::EVAL-FEATURE SYSTEM::DO-F
         SYSTEM::INSPECT-CHARACTER SYSTEM::REGEXP-CONV
         COMMON-LISP::TENTH SYSTEM::S-DATA-INCLUDED
         SYSTEM::GET-INSTREAM SYSTEM::REAL-ASINH
         ANSI-LOOP::LOOP-PATH-USER-DATA
         ANSI-LOOP::LOOP-UNIVERSE-ITERATION-KEYWORDS
         ANSI-LOOP::LOOP-COLLECTOR-P SYSTEM::LOGICAL-PATHNAME-HOST-P
         ANSI-LOOP::LOOP-MINIMAX-ANSWER-VARIABLE SYSTEM::WALK-THROUGH
         ANSI-LOOP::LOOP-COLLECTOR-CLASS
         ANSI-LOOP::LOOP-COLLECTOR-HISTORY
         ANSI-LOOP::LOOP-COLLECTOR-NAME
         COMMON-LISP::COMPILE-FILE-PATHNAME SLOOP::PARSE-LOOP-INITIALLY
         SYSTEM::RESTART-FUNCTION ANSI-LOOP::LOOP-UNIVERSE-ANSI
         SYSTEM::BKPT-FILE SYSTEM::WILD-DIR-ELEMENT-P FPE::ST-LOOKUP
         SYSTEM::S-DATA-PRINT-FUNCTION ANSI-LOOP::LOOP-MINIMAX-P
         SYSTEM::IHS-NOT-INTERPRETED-ENV SLOOP::PARSE-LOOP
         SYSTEM::DM-KEY-NOT-ALLOWED ANSI-LOOP::LOOP-MAKE-DESETQ
         SLOOP::RETURN-SLOOP-MACRO SYSTEM::IHS-FNAME COMMON-LISP::ABS
         COMMON-LISP::SIXTH ANSI-LOOP::LOOP-MINIMAX-TYPE
         SYSTEM::TRACE-ONE-PREPROCESS SYSTEM::INSPECT-STRUCTURE
         ANSI-LOOP::LOOP-CONSTRUCT-RETURN
         ANSI-LOOP::LOOP-UNIVERSE-TYPE-SYMBOLS SYSTEM::INSTREAM-STREAM
         SYSTEM::BEST-ARRAY-ELEMENT-TYPE SYSTEM::INSPECT-STRING
         COMMON-LISP::FIFTH COMMON-LISP::ATANH COMMON-LISP::PROVIDE
         SYSTEM::CHECK-TRACE-SPEC COMMON-LISP::THIRD
         SYSTEM::RESTART-TEST-FUNCTION COMMON-LISP::VECTOR-POP
         COMMON-LISP::BYTE-SIZE SYSTEM::INSTREAM-P
         SYSTEM::REWRITE-RESTART-CASE-CLAUSE SLOOP::REPEAT-SLOOP-MACRO
         SYSTEM::S-DATA-TYPE COMMON-LISP::RATIONAL
         ANSI-LOOP::LOOP-UNIVERSE-FOR-KEYWORDS SYSTEM::SETUP-INFO
         SYSTEM::INSPECT-CONS ANSI-LOOP::LOOP-PATH-INCLUSIVE-PERMITTED
         COMMON-LISP::INVOKE-DEBUGGER SYSTEM::FIND-DOCUMENTATION
         SYSTEM::RESTART-REPORT-FUNCTION SYSTEM::DIR-P
         SYSTEM::CANONICALIZE-PATHNAME-DIRECTORY SYSTEM::IDESCRIBE
         ANSI-LOOP::LOOP-MINIMAX-INFINITY-DATA
         SYSTEM::PRINT-SYMBOL-APROPOS SYSTEM::S-DATA-CONSTRUCTORS
         SYSTEM::SHORT-NAME SYSTEM::DM-BAD-KEY SYSTEM::PROCESS-ARGS
         COMMON-LISP::PHASE SYSTEM::DBL-EVAL
         SYSTEM::BREAK-BACKWARD-SEARCH-STACK COMMON-LISP::SEVENTH
         SYSTEM::SHOW-ENVIRONMENT SYSTEM::PNL1
         SYSTEM::INFO-NODE-FROM-POSITION ANSI-LOOP::DESTRUCTURING-SIZE
         COMMON-LISP::ASIN COMMON-LISP::FOURTH
         SLOOP::LOOP-COLLECT-KEYWORD-P SYSTEM::LEAP-YEAR-P
         SYSTEM::INSPECT-NUMBER SYSTEM::MAKE-FRAME
         ANSI-LOOP::LOOP-PATH-P
         COMMON-LISP::LOGICAL-PATHNAME-TRANSLATIONS
         SYSTEM::S-DATA-INCLUDES COMMON-LISP::SYNONYM-STREAM-SYMBOL
         SYSTEM::NODES-FROM-INDEX ANSI-LOOP::LOOP-MINIMAX-FLAG-VARIABLE
         ANSI-LOOP::LOOP-UNIVERSE-KEYWORDS SYSTEM::RE-QUOTE-STRING
         SYSTEM::S-DATA-FROZEN SYSTEM::COMPUTING-ARGS-P
         COMMON-LISP::TANH SYSTEM::LNP SYSTEM::TERMINAL-INTERRUPT
         SYSTEM::S-DATA-STATICP ANSI-LOOP::LOOP-UNIVERSE-P
         SYSTEM::INSTREAM-STREAM-NAME COMMON-LISP::FIRST
         SYSTEM::BKPT-FILE-LINE SYSTEM::S-DATA-SLOT-POSITION
         SYSTEM::IHS-VISIBLE SLOOP::SUBSTITUTE-SLOOP-BODY
         SYSTEM::S-DATA-CONC-NAME ANSI-LOOP::LOOP-PSEUDO-BODY
         SYSTEM::DWIM COMMON-LISP::SECOND SYSTEM::GET-NEXT-VISIBLE-FUN
         ANSI-LOOP::LOOP-HACK-ITERATION SLOOP::AVERAGING-SLOOP-MACRO
         SYSTEM::ENSURE-DIR-STRING SYSTEM::KNOWN-TYPE-P
         SYSTEM::GET-BYTE-STREAM-NCHARS SYSTEM::S-DATA-NAMED
         SYSTEM::INSPECT-ARRAY SYSTEM::INSPECT-PACKAGE
         SYSTEM::FIND-KCL-TOP-RESTART
         ANSI-LOOP::LOOP-UNIVERSE-TYPE-KEYWORDS
         COMMON-LISP::BYTE-POSITION SYSTEM::VERSION-PARSE
         SYSTEM::SEARCH-STACK SYSTEM::HOST-KEY
         ANSI-LOOP::LOOP-PATH-NAMES SYSTEM::S-DATA-SLOT-DESCRIPTIONS
         COMMON-LISP::ARRAY-DIMENSIONS SYSTEM::CONTEXT-P
         ANSI-LOOP::LOOP-MAKE-PSETQ SYSTEM::NUMBER-OF-DAYS-FROM-1900
         SYSTEM::PATHNAME-SYNONYM-STREAM-P SYSTEM::S-DATA-RAW
         COMMON-LISP::RESTART-NAME SLOOP::LOOP-LET-BINDINGS FPE::LOOKUP
         SYSTEM::BKPT-FUNCTION SYSTEM::PATHNAME-PARSE
         COMMON-LISP::LOGICAL-PATHNAME SYSTEM::LOGICAL-PATHNAMEP
         ANSI-LOOP::LOOP-COLLECTOR-TEMPVARS COMMON-LISP::COMPLEMENT
         SYSTEM::DIR-CONJ SYSTEM::INFO-GET-TAGS
         ANSI-LOOP::LOOP-CONSTANTP ANSI-LOOP::LOOP-EMIT-BODY
         COMMON-LISP::ACOSH COMMON-LISP::SINH
         ANSI-LOOP::LOOP-MAXMIN-COLLECTION COMMON-LISP::ISQRT
         ANSI-LOOP::LOOP-EMIT-FINAL-VALUE SYSTEM::EXPAND-PATH
         ANSI-LOOP::LOOP-CODE-DUPLICATION-THRESHOLD SYSTEM::PATCH-SHARP
         SYSTEM::ADD-TO-HOTLIST SYSTEM::INFO-GET-FILE
         SYSTEM::RESET-TRACE-DECLARATIONS SYSTEM::S-DATA-OFFSET
         COMMON-LISP::CIS SYSTEM::NODE-OFFSET
         SYSTEM::CHECK-DECLARATIONS COMMON-LISP::ACOS SYSTEM::RESTART-P
         FPE::GREF ANSI-LOOP::LOOP-TYPED-INIT SYSTEM::S-DATA-NAME
         ANSI-LOOP::LOOP-LIST-COLLECTION SYSTEM::BKPT-FORM
         SYSTEM::PRINT-IHS SYSTEM::MAKE-DEFPACKAGE-FORM
         SYSTEM::SIMPLE-ARRAY-P
         ANSI-LOOP::LOOP-UNIVERSE-IMPLICIT-FOR-REQUIRED
         SYSTEM::S-DATA-DOCUMENTATION SYSTEM::INSERT-BREAK-POINT
         ANSI-LOOP::LOOP-COLLECTOR-DTYPE
         ANSI-LOOP::LOOP-PATH-PREPOSITION-GROUPS
         SYSTEM::BREAK-FORWARD-SEARCH-STACK SYSTEM::MLP
         SYSTEM::RESTART-INTERACTIVE-FUNCTION COMMON-LISP::NINTH
         SYSTEM::TOGGLE-LOCAL-COMMON SLOOP::POINTER-FOR-COLLECT
         SYSTEM::FREEZE-DEFSTRUCT COMMON-LISP::TRUENAME
         COMMON-LISP::PROBE-FILE ANSI-LOOP::LOOP-UNIVERSE-PATH-KEYWORDS
         ANSI-LOOP::LOOP-COLLECTOR-DATA SYSTEM::S-DATA-P
         SYSTEM::PRINT-FRS COMMON-LISP::EIGHTH SYSTEM::FIX-LOAD-PATH
         SYSTEM::INSPECT-SYMBOL COMMON-LISP::COMPILER-MACRO-FUNCTION
         ANSI-LOOP::LOOP-MINIMAX-TEMP-VARIABLE
         SYSTEM::RESTRICT-STREAM-ELEMENT-TYPE COMMON-LISP::SIGNUM
         COMMON-LISP::COSH ANSI-LOOP::LOOP-PATH-FUNCTION
         COMMON-LISP::FIND-ALL-SYMBOLS SLOOP::TRANSLATE-NAME
         SYSTEM::FRS-KIND SYSTEM::SHOW-BREAK-POINT
         SLOOP::SLOOP-SLOOP-MACRO SYSTEM::UNIQUE-ID COMMON-LISP::ASINH
         SYSTEM::SEQTYPE ANSI-LOOP::LOOP-DO-THEREIS
         ANSI-LOOP::MAKE-ANSI-LOOP-UNIVERSE
         ANSI-LOOP::LOOP-MINIMAX-OPERATIONS COMMON-LISP::CONSTANTLY)) 
(COMMON-LISP::PROCLAIM
    '(COMMON-LISP::FTYPE
         (COMMON-LISP::FUNCTION (COMMON-LISP::*) COMMON-LISP::*)
         SYSTEM::SHOW-BREAK-VARIABLES SYSTEM::BREAK-BDS
         COMMON-LISP::MUFFLE-WARNING COMMON-LISP::CONTINUE
         SYSTEM::DBL-BACKTRACE SYSTEM::INFO-ERROR
         SYSTEM::BREAK-PREVIOUS SYSTEM::BREAK-NEXT SYSTEM::BREAK-LOCAL
         ANSI-LOOP::LOOP-OPTIONAL-TYPE SYSTEM::BREAK-QUIT
         SYSTEM::IHS-BACKTRACE SYSTEM::BREAK-VS)) 
(COMMON-LISP::PROCLAIM
    '(COMMON-LISP::FTYPE
         (COMMON-LISP::FUNCTION (COMMON-LISP::T COMMON-LISP::T)
             COMMON-LISP::*)
         ANSI-LOOP::ESTIMATE-CODE-SIZE SYSTEM::NEW-SEMI-COLON-READER
         SYSTEM::DO-REPL SYSTEM::NEWLINE SYSTEM::RESTART-REPORT
         SYSTEM::LIST-TOGGLE-CASE SYSTEM::FIND-DOC
         SYSTEM::SOURCE-PORTION ANSI-LOOP::ESTIMATE-CODE-SIZE-1)) 
(COMMON-LISP::PROCLAIM
    '(COMMON-LISP::FTYPE
         (COMMON-LISP::FUNCTION (COMMON-LISP::T COMMON-LISP::*)
             COMMON-LISP::T)
         COMMON-LISP::DIRECTORY ANSI-LOOP::LOOP-ERROR
         SYSTEM::NTH-STACK-FRAME COMMON-LISP::MAKE-ARRAY
         ANSI-LOOP::LOOP-COLLECT-PREPOSITIONAL-PHRASES
         SYSTEM::FILE-TO-STRING COMMON-LISP::PATHNAME-NAME
         SYSTEM::MGLIST COMMON-LISP::OPEN COMMON-LISP::MERGE-PATHNAMES
         SYSTEM::PROCESS-SOME-ARGS SLOOP::ADD-FROM-DATA
         COMMON-LISP::BIT SYSTEM::FILE-SEARCH
         COMMON-LISP::PATHNAME-HOST SLOOP::LOOP-ADD-TEMPS
         COMMON-LISP::DELETE-DUPLICATES SYSTEM::TO-REGEXP
         COMMON-LISP::CONCATENATE COMMON-LISP::PATHNAME-TYPE
         ANSI-LOOP::LOOP-WARN SYSTEM::LIST-MATCHES
         COMMON-LISP::PATHNAME-DEVICE SYSTEM::MGSUB
         COMMON-LISP::REMOVE-DUPLICATES
         COMMON-LISP::UPGRADED-ARRAY-ELEMENT-TYPE
         COMMON-LISP::TRANSLATE-LOGICAL-PATHNAME SYSTEM::LINK-EXPAND
         COMMON-LISP::ERROR COMMON-LISP::ARRAY-IN-BOUNDS-P
         COMMON-LISP::ARRAY-ROW-MAJOR-INDEX COMMON-LISP::SIGNAL
         SYSTEM::BREAK-LEVEL COMMON-LISP::PATHNAME-VERSION
         SYSTEM::INFO-SEARCH COMMON-LISP::SBIT COMMON-LISP::WARN
         COMMON-LISP::FIND-RESTART SYSTEM::BAD-SEQ-LIMIT
         COMMON-LISP::BIT-NOT COMMON-LISP::PATHNAME-DIRECTORY
         COMMON-LISP::READ-BYTE)) 
(COMMON-LISP::PROCLAIM
    '(COMMON-LISP::FTYPE
         (COMMON-LISP::FUNCTION COMMON-LISP::NIL COMMON-LISP::T)
         ANSI-LOOP::LOOP-WHEN-IT-VARIABLE SYSTEM::WINE-TMP-REDIRECT
         SYSTEM::CLEANUP SYSTEM::DEFAULT-SYSTEM-BANNER
         SYSTEM::TOP-LEVEL ANSI-LOOP::LOOP-GET-PROGN SYSTEM::TEST-ERROR
         SLOOP::PARSE-LOOP-DO ANSI-LOOP::LOOP-DO-NAMED
         SYSTEM::GET-INDEX-NODE SYSTEM::INIT-BREAK-POINTS
         SLOOP::PARSE-LOOP-COLLECT SLOOP::LOOP-PEEK
         SYSTEM::INSPECT-INDENT ANSI-LOOP::LOOP-DO-REPEAT
         SYSTEM::SET-CURRENT ANSI-LOOP::LOOP-BIND-BLOCK
         SYSTEM::DM-TOO-MANY-ARGUMENTS SYSTEM::SET-UP-TOP-LEVEL
         SYSTEM::DBL SYSTEM::INSPECT-INDENT-1 SLOOP::PARSE-LOOP1
         SLOOP::PARSE-LOOP-WHEN SYSTEM::SET-ENV
         SYSTEM::INSPECT-READ-LINE SYSTEM::GET-SIG-FN-NAME
         SYSTEM::DM-TOO-FEW-ARGUMENTS ANSI-LOOP::LOOP-POP-SOURCE
         SYSTEM::GET-TEMP-DIR SYSTEM::READ-EVALUATED-FORM
         SLOOP::LOOP-UN-POP SLOOP::PARSE-ONE-WHEN-CLAUSE
         SYSTEM::DEFAULT-INFO-HOTLIST
         COMMON-LISP::LISP-IMPLEMENTATION-VERSION
         ANSI-LOOP::LOOP-DO-INITIALLY SYSTEM::SHOW-RESTARTS
         ANSI-LOOP::LOOP-ITERATION-DRIVER ANSI-LOOP::LOOP-DO-FINALLY
         ANSI-LOOP::LOOP-DO-RETURN COMMON-LISP::TYPE-ERROR
         SYSTEM::STEP-READ-LINE SYSTEM::KCL-TOP-RESTARTS
         ANSI-LOOP::LOOP-DO-DO SYSTEM::SETUP-LINEINFO
         SYSTEM::ILLEGAL-BOA ANSI-LOOP::LOOP-DO-WITH
         SLOOP::PARSE-LOOP-FOR SLOOP::LOOP-POP ANSI-LOOP::LOOP-GET-FORM
         SYSTEM::ALL-TRACE-DECLARATIONS ANSI-LOOP::LOOP-CONTEXT)) 
(COMMON-LISP::PROCLAIM
    '(COMMON-LISP::FTYPE
         (COMMON-LISP::FUNCTION (COMMON-LISP::T)
             COMMON-LISP::HASH-TABLE)
         SYSTEM::CONTEXT-SPICE)) 
(COMMON-LISP::MAPC
    (COMMON-LISP::LAMBDA (COMPILER::X)
      (COMMON-LISP::SETF
          (COMMON-LISP::GET COMPILER::X 'COMPILER::PROCLAIMED-CLOSURE)
          COMMON-LISP::T))
    '(SYSTEM::DEFINE-STRUCTURE SYSTEM::TRACE-ONE SYSTEM::WARNINGP
         FPE::BREAK-ON-FLOATING-POINT-EXCEPTIONS SYSTEM::SI-CLASS-OF
         SYSTEM::CONDITION-CLASS-P SYSTEM::SI-CLASS-NAME
         SYSTEM::AUTOLOAD-MACRO SYSTEM::SI-CLASS-PRECEDENCE-LIST
         SYSTEM::SIMPLE-CONDITION-CLASS-P SYSTEM::CONDITIONP
         SYSTEM::SI-CLASSP SYSTEM::SI-FIND-CLASS SYSTEM::UNTRACE-ONE
         SYSTEM::AUTOLOAD SYSTEM::MAKE-ACCESS-FUNCTION)) 
(COMMON-LISP::PROCLAIM
    '(COMMON-LISP::FTYPE
         (COMMON-LISP::FUNCTION
             (COMMON-LISP::T COMMON-LISP::T COMMON-LISP::T
                 COMMON-LISP::*)
             COMMON-LISP::T)
         SLOOP::LOOP-DECLARE-BINDING COMMON-LISP::SUBSTITUTE-IF-NOT
         COMMON-LISP::SUBSTITUTE-IF SYSTEM::CHECK-TYPE-SYMBOL
         SYSTEM::DIR-PARSE
         ANSI-LOOP::LOOP-PACKAGE-SYMBOLS-ITERATION-PATH
         COMMON-LISP::NSUBSTITUTE-IF
         ANSI-LOOP::LOOP-HASH-TABLE-ITERATION-PATH
         SYSTEM::PUSH-LET-BINDING ANSI-LOOP::LOOP-MAKE-VARIABLE
         COMMON-LISP::MAP COMMON-LISP::TRANSLATE-PATHNAME
         ANSI-LOOP::ADD-LOOP-PATH COMMON-LISP::NSUBSTITUTE-IF-NOT
         SYSTEM::MATCH-COMPONENT COMMON-LISP::SUBSTITUTE
         ANSI-LOOP::LOOP-SEQUENCE-ELEMENTS-PATH SYSTEM::COMPLETE-PROP
         COMMON-LISP::NSUBSTITUTE)) 
(COMMON-LISP::PROCLAIM
    '(COMMON-LISP::FTYPE
         (COMMON-LISP::FUNCTION
             (COMMON-LISP::T COMMON-LISP::T COMMON-LISP::T)
             COMMON-LISP::T)
         SYSTEM::MFR SYSTEM::RESTART-CASE-EXPRESSION-CONDITION
         ANSI-LOOP::LOOP-FOR-BEING FPE::REF
         ANSI-LOOP::LOOP-MAKE-ITERATION-VARIABLE SYSTEM::MAKE-T-TYPE
         ANSI-LOOP::LOOP-ANSI-FOR-EQUALS SYSTEM::WARN-VERSION
         ANSI-LOOP::LOOP-TRANSLATE SYSTEM::TO-REGEXP1
         SYSTEM::APPLY-DISPLAY-FUN ANSI-LOOP::LOOP-FOR-IN
         ANSI-LOOP::LOOP-SUM-COLLECTION SYSTEM::SHARP-A-READER
         SYSTEM::GET-SLOT-POS ANSI-LOOP::LOOP-FOR-ACROSS
         SYSTEM::SHARP-V-READER SYSTEM::SETF-EXPAND-1
         SYSTEM::CHECK-S-DATA SYSTEM::DM-VL COMMON-LISP::DPB
         ANSI-LOOP::LOOP-STANDARD-EXPANSION COMMON-LISP::DEPOSIT-FIELD
         ANSI-LOOP::LOOP-FOR-ON ANSI-LOOP::HIDE-VARIABLE-REFERENCE
         SYSTEM::FLOATING-POINT-ERROR ANSI-LOOP::PRINT-LOOP-UNIVERSE
         SYSTEM::LOGICAL-PATHNAME-PARSE SYSTEM::DEFMACRO*
         SYSTEM::MAKE-BREAK-POINT
         SLOOP::LOOP-PARSE-ADDITIONAL-COLLECTIONS
         SYSTEM::SHARP-P-READER SYSTEM::SHARP-U-READER
         SYSTEM::CHECK-TRACE-ARGS)) 
(COMMON-LISP::PROCLAIM
    '(COMMON-LISP::FTYPE
         (COMMON-LISP::FUNCTION
             (COMMON-LISP::T COMMON-LISP::T COMMON-LISP::T
                 COMMON-LISP::T COMMON-LISP::T COMMON-LISP::T)
             COMMON-LISP::T)
         SYSTEM::DO-ARG-COUNT-ERROR SYSTEM::PUSH-SUB-LIST-BINDING)) 
(COMMON-LISP::PROCLAIM
    '(COMMON-LISP::FTYPE
         (COMMON-LISP::FUNCTION
             (COMMON-LISP::T COMMON-LISP::T COMMON-LISP::*)
             COMMON-LISP::T)
         COMMON-LISP::SUBSETP COMMON-LISP::BIT-EQV
         SLOOP::IN-ARRAY-SLOOP-FOR SYSTEM::INTERNAL-COUNT
         COMMON-LISP::DELETE SYSTEM::PROCESS-ERROR
         COMMON-LISP::FIND-IF-NOT COMMON-LISP::NOTEVERY
         COMMON-LISP::MAP-INTO SYSTEM::INTERNAL-COUNT-IF-NOT
         COMMON-LISP::ADJUST-ARRAY COMMON-LISP::NSET-EXCLUSIVE-OR
         COMMON-LISP::FIND-IF SYSTEM::INTERNAL-COUNT-IF
         COMMON-LISP::REMOVE COMMON-LISP::READ-SEQUENCE
         COMMON-LISP::CERROR COMMON-LISP::SEARCH COMMON-LISP::BIT-ANDC1
         COMMON-LISP::REMOVE-IF COMMON-LISP::VECTOR-PUSH-EXTEND
         COMMON-LISP::WRITE-SEQUENCE COMMON-LISP::NINTERSECTION
         COMMON-LISP::SET-DIFFERENCE COMMON-LISP::FIND
         COMMON-LISP::MISMATCH COMMON-LISP::POSITION-IF
         COMMON-LISP::TYPEP COMMON-LISP::COUNT-IF-NOT
         COMMON-LISP::REPLACE COMMON-LISP::NUNION
         COMMON-LISP::INTERSECTION COMMON-LISP::FILL
         COMMON-LISP::COUNT-IF SYSTEM::BREAK-CALL COMMON-LISP::BIT-ORC1
         COMMON-LISP::NOTANY SLOOP::PARSE-LOOP-MACRO
         COMMON-LISP::BIT-ORC2 SYSTEM::WREADDIR3 COMMON-LISP::BIT-ANDC2
         COMMON-LISP::EVERY COMMON-LISP::BIT-AND
         COMMON-LISP::DELETE-IF-NOT COMMON-LISP::BIT-IOR
         SYSTEM::WALK-DIR COMMON-LISP::SET-EXCLUSIVE-OR
         COMMON-LISP::DELETE-IF SYSTEM::MME2 COMMON-LISP::BIT-NOR
         COMMON-LISP::NSET-DIFFERENCE COMMON-LISP::UNION
         COMMON-LISP::BIT-NAND COMMON-LISP::POSITION
         COMMON-LISP::BIT-XOR COMMON-LISP::POSITION-IF-NOT
         COMMON-LISP::COUNT COMMON-LISP::MAKE-SEQUENCE
         COMMON-LISP::SOME SYSTEM::FIND-IHS
         ANSI-LOOP::LOOP-CHECK-DATA-TYPE COMMON-LISP::REMOVE-IF-NOT
         SLOOP::LOOP-ADD-BINDING)) 
(COMMON-LISP::PROCLAIM
    '(COMMON-LISP::FTYPE
         (COMMON-LISP::FUNCTION
             (COMMON-LISP::T COMMON-LISP::T COMMON-LISP::T
                 COMMON-LISP::T)
             COMMON-LISP::T)
         SYSTEM::MAYBE-BREAK SYSTEM::FIND-LINE-IN-FUN
         SLOOP::FIRST-SLOOP-FOR SYSTEM::SETF-STRUCTURE-ACCESS
         SYSTEM::COERCE-TO-CONDITION SLOOP::FIRST-USE-SLOOP-FOR
         SYSTEM::CALL-TEST SYSTEM::ELSUB1
         ANSI-LOOP::LOOP-FOR-ARITHMETIC SYSTEM::ELEMENT)) 
(COMMON-LISP::PROCLAIM
    '(COMMON-LISP::FTYPE
         (COMMON-LISP::FUNCTION (COMMON-LISP::T) COMMON-LISP::FIXNUM)
         SYSTEM::S-DATA-SIZE SYSTEM::INSTREAM-LINE SYSTEM::LENEL
         SYSTEM::THE-START FPE::REG-LOOKUP SYSTEM::S-DATA-LENGTH)) 
(COMMON-LISP::PROCLAIM
    '(COMMON-LISP::FTYPE
         (COMMON-LISP::FUNCTION
             (COMMON-LISP::T COMMON-LISP::T COMMON-LISP::T
                 COMMON-LISP::T COMMON-LISP::*)
             COMMON-LISP::T)
         SYSTEM::PRINT-STACK-FRAME COMMON-LISP::MERGE
         SLOOP::DEF-LOOP-INTERNAL)) 
(COMMON-LISP::PROCLAIM
    '(COMMON-LISP::FTYPE
         (COMMON-LISP::FUNCTION
             (COMMON-LISP::T COMMON-LISP::T COMMON-LISP::T
                 COMMON-LISP::T COMMON-LISP::T)
             COMMON-LISP::T)
         SYSTEM::MAKE-PREDICATE SYSTEM::MAKE-CONSTRUCTOR
         SYSTEM::DO-BREAK-LEVEL)) 
(COMMON-LISP::PROCLAIM
    '(COMMON-LISP::FTYPE
         (COMMON-LISP::FUNCTION
             (COMMON-LISP::T COMMON-LISP::T COMMON-LISP::T
                 COMMON-LISP::T COMMON-LISP::T COMMON-LISP::T
                 COMMON-LISP::*)
             COMMON-LISP::T)
         COMMON-LISP::ENCODE-UNIVERSAL-TIME)) 
(COMMON-LISP::PROCLAIM
    '(COMMON-LISP::FTYPE
         (COMMON-LISP::FUNCTION
             (COMMON-LISP::T COMMON-LISP::T COMMON-LISP::T
                 COMMON-LISP::T COMMON-LISP::T COMMON-LISP::T
                 COMMON-LISP::T COMMON-LISP::T COMMON-LISP::T
                 COMMON-LISP::T)
             COMMON-LISP::T)
         ANSI-LOOP::LOOP-SEQUENCER)) 
(COMMON-LISP::PROCLAIM
    '(COMMON-LISP::FTYPE
         (COMMON-LISP::FUNCTION
             (COMMON-LISP::T COMMON-LISP::T COMMON-LISP::T
                 COMMON-LISP::T COMMON-LISP::T COMMON-LISP::*)
             COMMON-LISP::T)
         SYSTEM::UNIVERSAL-ERROR-HANDLER)) 
(COMMON-LISP::PROCLAIM
    '(COMMON-LISP::FTYPE
         (COMMON-LISP::FUNCTION
             (COMMON-LISP::T COMMON-LISP::T
                 (COMMON-LISP::INTEGER -9223372036854775808
                     9223372036854775807))
             COMMON-LISP::T)
         SYSTEM::SHARP-SHARP-READER SYSTEM::SHARP-EQ-READER)) 
(COMMON-LISP::PROCLAIM
    '(COMMON-LISP::FTYPE
         (COMMON-LISP::FUNCTION (COMMON-LISP::T COMMON-LISP::*)
             COMMON-LISP::*)
         COMMON-LISP::PARSE-NAMESTRING COMMON-LISP::FFLOOR
         SYSTEM::BREAK-FUNCTION SYSTEM::PARSE-BODY-HEADER
         SYSTEM::APROPOS-DOC COMMON-LISP::USE-VALUE
         COMMON-LISP::READ-FROM-STRING COMMON-LISP::GET-SETF-EXPANSION
         COMMON-LISP::WRITE-TO-STRING
         COMMON-LISP::DECODE-UNIVERSAL-TIME
         COMMON-LISP::WILD-PATHNAME-P SYSTEM::INFO SYSTEM::STEPPER
         SYSTEM::SHOW-INFO ANSI-LOOP::LOOP-CONSTANT-FOLD-IF-POSSIBLE
         COMMON-LISP::APROPOS SYSTEM::GET-SETF-METHOD-MULTIPLE-VALUE
         COMMON-LISP::INVOKE-RESTART COMMON-LISP::STORE-VALUE
         COMMON-LISP::ENSURE-DIRECTORIES-EXIST COMMON-LISP::FTRUNCATE
         COMMON-LISP::REQUIRE COMMON-LISP::APROPOS-LIST SYSTEM::NLOAD
         SYSTEM::PRINT-DOC COMMON-LISP::FCEILING COMMON-LISP::FROUND)) 
(COMMON-LISP::PROCLAIM
    '(COMMON-LISP::FTYPE
         (COMMON-LISP::FUNCTION (COMMON-LISP::T COMMON-LISP::T)
             COMMON-LISP::T)
         ANSI-LOOP::LOOP-TMEMBER SYSTEM::DM-NTH-CDR SYSTEM::MME3
         SLOOP::=-SLOOP-FOR SLOOP::L-EQUAL COMMON-LISP::LDB-TEST
         SLOOP::MINIMIZE-SLOOP-COLLECT SYSTEM::SAFE-EVAL
         COMMON-LISP::LOGORC1 SYSTEM::DBL-UP
         SLOOP::THEREIS-SLOOP-COLLECT SYSTEM::GET-INFO-CHOICES
         SLOOP::IN-PACKAGE-SLOOP-MAP SYSTEM::LIST-DELQ
         ANSI-LOOP::LOOP-LOOKUP-KEYWORD SYSTEM::GET-NODES
         SLOOP::IN-CAREFULLY-SLOOP-FOR SLOOP::THE-TYPE
         SYSTEM::LEFT-PARENTHESIS-READER SYSTEM::MATCH-DIMENSIONS
         SYSTEM::SUPER-GO SLOOP::LOGXOR-SLOOP-COLLECT
         SYSTEM::COERCE-TO-STRING SYSTEM::BREAK-STEP-INTO
         SYSTEM::CONDITION-PASS COMMON-LISP::LDB SYSTEM::SUB-INTERVAL-P
         SYSTEM::SETF-EXPAND SLOOP::PARSE-LOOP-MAP
         COMMON-LISP::WRITE-BYTE SYSTEM::MSUB
         SLOOP::COUNT-SLOOP-COLLECT SLOOP::DESETQ1
         SYSTEM::PARSE-SLOT-DESCRIPTION SYSTEM::ALL-MATCHES
         SYSTEM::INFO-AUX FPE::READ-OPERANDS FPE::PAREN-READER
         COMMON-LISP::LOGANDC2 SLOOP::SUM-SLOOP-COLLECT
         COMMON-LISP::PATHNAME-MATCH-P SYSTEM::SEQUENCE-CURSOR
         COMMON-LISP::DOCUMENTATION SYSTEM::KEYWORD-SUPPLIED-P
         COMMON-LISP::LOGORC2 COMMON-LISP::LOGNOR
         SLOOP::NEVER-SLOOP-COLLECT SYSTEM::CHECK-SEQ-START-END
         COMMON-LISP::COERCE FPE::%-READER SLOOP::MAKE-VALUE
         SYSTEM::PROCESS-CASE SYSTEM::DM-V COMMON-LISP::BYTE
         FPE::READ-INSTRUCTION SLOOP::IN-TABLE-SLOOP-MAP
         SYSTEM::DISPLAY-COMPILED-ENV ANSI-LOOP::LOOP-DO-IF
         FPE::0-READER SLOOP::ALWAYS-SLOOP-COLLECT
         ANSI-LOOP::LOOP-DECLARE-VARIABLE SYSTEM::DISPLAY-ENV
         SYSTEM::IN-INTERVAL-P SYSTEM::LOOKUP-KEYWORD
         SYSTEM::ITERATE-OVER-BKPTS COMMON-LISP::NTHCDR
         ANSI-LOOP::LOOP-DO-WHILE COMMON-LISP::LOGANDC1
         SYSTEM::*BREAK-POINTS* SYSTEM::DOT-DIR-P FPE::RF
         SYSTEM::GET-MATCH SYSTEM::SETF-HELPER
         SYSTEM::SETF-LOGICAL-PATHNAME-TRANSLATIONS SYSTEM::OBJLT
         ANSI-LOOP::LOOP-TASSOC COMPILER::COMPILER-DEF-HOOK
         SYSTEM::SET-DIR SYSTEM::ADD-FILE SLOOP::MAXIMIZE-SLOOP-COLLECT
         SYSTEM::QUOTATION-READER SYSTEM::INCREMENT-CURSOR
         ANSI-LOOP::MAKE-LOOP-MINIMAX COMMON-LISP::LOGNAND
         SYSTEM::OVERWRITE-SLOT-DESCRIPTIONS SYSTEM::RECURSE-DIR
         SYSTEM::BREAK-STEP-NEXT ANSI-LOOP::LOOP-MAYBE-BIND-FORM
         SYSTEM::SET-BACK SLOOP::COLLATE-SLOOP-COLLECT
         SYSTEM::VECTOR-PUSH-STRING SYSTEM::SUBSTRINGP SYSTEM::DM-NTH
         SYSTEM::?PUSH SLOOP::IN-FRINGE-SLOOP-MAP
         SYSTEM::GET-LINE-OF-FORM ANSI-LOOP::LOOP-DO-ALWAYS
         ANSI-LOOP::HIDE-VARIABLE-REFERENCES COMMON-LISP::LOGTEST
         COMMON-LISP::VECTOR-PUSH COMMON-LISP::NTH
         ANSI-LOOP::LOOP-NOTE-MINIMAX-OPERATION SYSTEM::LPSUB
         ANSI-LOOP::LOOP-TEQUAL)) 
(COMMON-LISP::PROCLAIM
    '(COMMON-LISP::FTYPE
         (COMMON-LISP::FUNCTION COMMON-LISP::NIL COMMON-LISP::*)
         ANSI-LOOP::LOOP-DO-FOR SYSTEM::BREAK-HELP
         SYSTEM::SIMPLE-BACKTRACE SYSTEM::GCL-TOP-LEVEL
         SYSTEM::BREAK-RESUME SYSTEM::BREAK-CURRENT
         SYSTEM::BREAK-MESSAGE)) 
(COMMON-LISP::PROCLAIM
    '(COMMON-LISP::FTYPE
         (COMMON-LISP::FUNCTION
             (COMMON-LISP::T COMMON-LISP::T COMMON-LISP::T)
             COMMON-LISP::*)
         SYSTEM::RESTART-PRINT SYSTEM::SHARP-+-READER
         ANSI-LOOP::LOOP-GET-COLLECTION-INFO SYSTEM::SHARP---READER
         SYSTEM::VERIFY-KEYWORDS SYSTEM::READ-INSPECT-COMMAND
         SYSTEM::SHARP-S-READER SYSTEM::LIST-MERGE-SORT)) 
(COMMON-LISP::PROCLAIM
    '(COMMON-LISP::FTYPE
         (COMMON-LISP::FUNCTION
             (COMMON-LISP::T COMMON-LISP::T COMMON-LISP::*)
             COMMON-LISP::*)
         COMMON-LISP::SUBTYPEP SYSTEM::PARSE-BODY
         COMMON-LISP::STABLE-SORT COMMON-LISP::SORT
         SYSTEM::EXPAND-WILD-DIRECTORY COMMON-LISP::REDUCE
         SLOOP::FIND-IN-ORDERED-LIST)) 
(COMMON-LISP::PROCLAIM
    '(COMMON-LISP::FTYPE
         (COMMON-LISP::FUNCTION
             (COMMON-LISP::T COMMON-LISP::T COMMON-LISP::T
                 COMMON-LISP::*)
             COMMON-LISP::*)
         SYSTEM::MASET)) 
(COMMON-LISP::PROCLAIM
    '(COMMON-LISP::FTYPE
         (COMMON-LISP::FUNCTION
             (COMMON-LISP::T COMMON-LISP::T COMMON-LISP::T
                 COMMON-LISP::T COMMON-LISP::T COMMON-LISP::*)
             COMMON-LISP::*)
         SYSTEM::PARSE-DEFMACRO-LAMBDA-LIST SYSTEM::PARSE-DEFMACRO)) 
(COMMON-LISP::PROCLAIM
    '(COMMON-LISP::FTYPE
         (COMMON-LISP::FUNCTION
             (COMMON-LISP::T COMMON-LISP::T COMMON-LISP::T
                 COMMON-LISP::T COMMON-LISP::T COMMON-LISP::T
                 COMMON-LISP::T COMMON-LISP::T)
             COMMON-LISP::*)
         SYSTEM::PUSH-OPTIONAL-BINDING)) 
(COMMON-LISP::PROCLAIM
    '(COMMON-LISP::FTYPE
         (COMMON-LISP::FUNCTION
             (COMMON-LISP::T COMMON-LISP::T COMMON-LISP::T
                 COMMON-LISP::T COMMON-LISP::T COMMON-LISP::T
                 COMMON-LISP::T)
             COMMON-LISP::*)
         SYSTEM::TRACE-CALL)) 
(COMMON-LISP::PROCLAIM
    '(COMMON-LISP::FTYPE
         (COMMON-LISP::FUNCTION (COMMON-LISP::T COMMON-LISP::T)
             COMMON-LISP::FIXNUM)
         SYSTEM::GET-NODE-INDEX SYSTEM::THE-END SYSTEM::RELATIVE-LINE
         ANSI-LOOP::DUPLICATABLE-CODE-P)) 
(COMMON-LISP::PROCLAIM
    '(COMMON-LISP::FTYPE
         (COMMON-LISP::FUNCTION (COMMON-LISP::*) COMMON-LISP::T)
         ANSI-LOOP::LOOP-DISALLOW-CONDITIONAL SYSTEM::MAYBE-CLEAR-INPUT
         COMMON-LISP::ABORT SYSTEM::STEP-INTO
         SYSTEM::DESCRIBE-ENVIRONMENT SLOOP::PARSE-LOOP-WITH
         ANSI-LOOP::MAKE-STANDARD-LOOP-UNIVERSE COMMON-LISP::Y-OR-N-P
         ANSI-LOOP::LOOP-GENTEMP SYSTEM::DBL-READ
         ANSI-LOOP::MAKE-LOOP-UNIVERSE SYSTEM::MAKE-S-DATA
         ANSI-LOOP::MAKE-LOOP-PATH SLOOP::PARSE-LOOP-DECLARE
         COMMON-LISP::DRIBBLE SYSTEM::TRANSFORM-KEYWORDS
         SYSTEM::STEP-NEXT COMMON-LISP::MAKE-PATHNAME
         COMMON-LISP::BREAK COMMON-LISP::COMPUTE-RESTARTS
         ANSI-LOOP::MAKE-LOOP-COLLECTOR COMMON-LISP::YES-OR-NO-P
         ANSI-LOOP::MAKE-LOOP-MINIMAX-INTERNAL SYSTEM::LOC
         SYSTEM::BREAK-LOCALS SYSTEM::MAKE-INSTREAM COMMON-LISP::VECTOR
         SYSTEM::MAKE-RESTART SYSTEM::MAKE-CONTEXT
         SYSTEM::CURRENT-STEP-FUN)) 
(COMMON-LISP::PROCLAIM
    '(COMMON-LISP::FTYPE
         (COMMON-LISP::FUNCTION (COMMON-LISP::T) COMMON-LISP::*)
         COMMON-LISP::INVOKE-RESTART-INTERACTIVELY
         ANSI-LOOP::NAMED-VARIABLE SYSTEM::FIND-DECLARATIONS
         SYSTEM::INSTREAM-NAME COMMON-LISP::INSPECT
         ANSI-LOOP::LOOP-LIST-STEP
         ANSI-LOOP::LOOP-OPTIMIZATION-QUANTITIES SYSTEM::INFO-SUBFILE
         COMMON-LISP::DESCRIBE SYSTEM::INSPECT-OBJECT
         SYSTEM::END-WAITING COMMON-LISP::PRINC-TO-STRING
         SYSTEM::BREAK-GO SYSTEM::ALOAD SYSTEM::GET-&ENVIRONMENT
         COMMON-LISP::PRIN1-TO-STRING
         SYSTEM::BREAK-LEVEL-INVOKE-RESTART SYSTEM::WAITING)) 
(COMMON-LISP::PROCLAIM
    '(COMMON-LISP::FTYPE
         (COMMON-LISP::FUNCTION
             ((COMMON-LISP::INTEGER -9223372036854775808
                  9223372036854775807))
             COMMON-LISP::T)
         SYSTEM::PUSH-CONTEXT SYSTEM::GET-CONTEXT)) 
(COMMON-LISP::PROCLAIM
    '(COMMON-LISP::FTYPE
         (COMMON-LISP::FUNCTION (COMMON-LISP::T)
             (COMMON-LISP::VALUES COMMON-LISP::T COMMON-LISP::T))
         SYSTEM::MAKE-KEYWORD)) 
(COMMON-LISP::PROCLAIM
    '(COMMON-LISP::FTYPE
         (COMMON-LISP::FUNCTION
             ((COMMON-LISP::VECTOR COMMON-LISP::CHARACTER
                  COMMON-LISP::*))
             COMMON-LISP::T)
         SYSTEM::RESET-SYS-PATHS SYSTEM::COERCE-SLASH-TERMINATED)) 
(COMMON-LISP::PROCLAIM
    '(COMMON-LISP::FTYPE
         (COMMON-LISP::FUNCTION (COMMON-LISP::T)
             (COMMON-LISP::VECTOR COMMON-LISP::T))
         SYSTEM::CONTEXT-VEC)) 
(COMMON-LISP::PROCLAIM
    '(COMMON-LISP::FTYPE
         (COMMON-LISP::FUNCTION
             ((COMMON-LISP::INTEGER -9223372036854775808
                  9223372036854775807))
             COMMON-LISP::FIXNUM)
         SYSTEM::DBL-WHAT-FRAME FPE::FE-ENABLE)) 
(COMMON-LISP::PROCLAIM
    '(COMMON-LISP::FTYPE
         (COMMON-LISP::FUNCTION (COMMON-LISP::T)
             (COMMON-LISP::OR COMMON-LISP::NULL
                 COMMON-LISP::HASH-TABLE))
         SYSTEM::CONTEXT-HASH)) 