
(IN-PACKAGE "CONDITIONS") 
(PROCLAIM '(FTYPE (FUNCTION (*) (*)) SYSTEM::CLCS-BREAK-QUIT)) 
(PROCLAIM '(FTYPE (FUNCTION (T) (*)) CONDITION-BACKTRACE)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T T T) *)
            |(PCL::FAST-METHOD PRINT-OBJECT (SIMPLE-CONDITION T))|
            |(PCL::FAST-METHOD PRINT-OBJECT (TYPE-ERROR T))|
            |(PCL::FAST-METHOD PRINT-OBJECT (CASE-FAILURE T))|
            |(PCL::FAST-METHOD PRINT-OBJECT (END-OF-FILE T))|
            |(PCL::FAST-METHOD PRINT-OBJECT (PACKAGE-ERROR T))|
            COERCE-TO-CONDITION
            |(PCL::FAST-METHOD PRINT-OBJECT (UNBOUND-VARIABLE T))|
            |(PCL::FAST-METHOD PRINT-OBJECT (UNDEFINED-FUNCTION T))|
            |(PCL::FAST-METHOD PRINT-OBJECT (ABORT-FAILURE T))|
            |(PCL::FAST-METHOD PRINT-OBJECT (INTERNAL-ERROR T))|
            |(PCL::FAST-METHOD PRINT-OBJECT (INTERNAL-SIMPLE-ERROR T))|)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T T T T *) *) CLCS-UNIVERSAL-ERROR-HANDLER)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T T) *) EXECUTE-DEBUGGER-COMMAND
            RESTART-PRINT)) 
(PROCLAIM '(FTYPE (FUNCTION (T T T) T) ACCUMULATE-CASES)) 
(PROCLAIM '(FTYPE (FUNCTION (T T *) T) CERROR)) 
(PROCLAIM '(FTYPE (FUNCTION (T T T *) T) SET-INTERNAL-ERROR)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T T T) T)
            |(PCL::FAST-METHOD PRINT-OBJECT (CONDITION T))|)) 
(PROCLAIM
    '(FTYPE (FUNCTION NIL *) ABORT SYSTEM::BREAK-RESUME CONTINUE
            MUFFLE-WARNING SYSTEM::BREAK-HELP)) 
(PROCLAIM
    '(FTYPE (FUNCTION NIL T) READ-DEBUG-COMMAND KCL-TOP-RESTARTS
            INITIALIZE-INTERNAL-ERROR-TABLE READ-EVALUATED-FORM
            INSTALL-CLCS-SYMBOLS REVERT-CLCS-SYMBOLS)) 
(PROCLAIM '(FTYPE (FUNCTION (*) *) INVOKE-DEBUGGER CLCS-COMPILE)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T) *) COMPILER::CMP-TOPLEVEL-EVAL CLCS-ERROR-SET
            SYSTEM::CLCS-BREAK-LEVEL-INVOKE-RESTART
            SIMPLE-ASSERTION-FAILURE INVOKE-RESTART-INTERACTIVELY
            STORE-VALUE USE-VALUE)) 
(PROCLAIM
    '(FTYPE (FUNCTION (*) T) SHOW-RESTARTS MAKE-RESTART BREAK
            COMPUTE-RESTARTS)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T *) *) ERROR MAKE-CONDITION INVOKE-RESTART
            CLCS-COMPILE-FILE CLCS-LOAD CLCS-OPEN)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T) T) UNIQUE-ID MAKE-KCL-TOP-RESTART
            FIND-KCL-TOP-RESTART STANDARD-DEBUGGER
            SIMPLE-CONDITION-CLASS-P RESTART-P RESET-FUNCTION
            RESTART-NAME SYSTEM::CLCS-TERMINAL-INTERRUPT
            RESTART-FUNCTION RESTART-REPORT-FUNCTION
            RESTART-INTERACTIVE-FUNCTION ESCAPE-SPECIAL-CASES-REPLACE
            REVERT-SYMBOL CONDITIONP CONDITION-CLASS-P)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T) *) RESTART-REPORT ASSERT-PROMPT
            PARSE-KEYWORD-PAIRS)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T *) T) WARN SIGNAL FIND-RESTART
            SYSTEM::CLCS-BREAK-LEVEL)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T) T) SIMPLE-CONDITION-PRINTER
            INTERNAL-SIMPLE-ERROR-PRINTER ASSERT-REPORT INSTALL-SYMBOL)) 